
include:
  - board: akdk_bt1
    shield: filled2_rev2
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artificial-name: filled2_rev2
  - board: akdk_bt1
    shield: settings_reset
    artificial-name: settings_reset-akdk_bt1-zmk
